name: calcolapizza
description: Le esatte dosi per i tuoi impasti in pochi secondi

version: 1.0.0+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
    
  bubble_bottom_bar: ^1.2.0
  cupertino_icons: ^0.1.2
  facebook_audience_network: ^0.3.3
  flushbar: 1.5.3
  font_awesome_flutter: ^8.4.0
  package_info: ^0.4.0+4
  path_provider: ^1.1.0
  provider: ^3.0.0+1
  share: ^0.6.1+1
  sqflite: ^1.1.5
  url_launcher: ^5.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_icon.png
    - assets/images/no_data_pizza.png
    - assets/lang/lang.json
